- name: Copy tailscale install script
  copy:
    dest: /usr/local/bin/tailscale-install.sh
    group: root
    mode: 0744
    owner: root
    src: files/tailscale-install.sh

- name: Disable enterprise packages repo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Disable ceph packages repo
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/ceph.list
    state: absent

- name: Enable cronjob for dead mans snitch
  ansible.builtin.cron:
    name: "deadmansnitch"
    minute: "*"
    hour: "*"
    job: "curl https://hc-ping.com/f3908729-f7ab-49f3-851b-5c06157a7f4c"

- name: install proxmoxer
  apt: name=python3-proxmoxer state=present update_cache=yes

# For automatically turning off screen
- name: install vbetool
  apt: name=vbetool state=present update_cache=yes

- name: Enable cronjob for vbetool
  ansible.builtin.cron:
    name: "turn off display"
    special_time: reboot
    job: "setterm --blank 1"

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: enable ipv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Check if tailscale already installed
  stat:
    path: /usr/bin/tailscale
  register: tailscale_bin

- name: Install tailscale
  command: /usr/local/bin/tailscale-install.sh
  when: not tailscale_bin.stat.exists

- name: Start tailscale
  command: tailscale up --accept-dns=false --advertise-routes=192.168.80.0/24 --authkey="{{ tailscale_key }}"
  when: not tailscale_bin.stat.exists

# Run `pveam available to list available templates`
- name: Check if debian template file exists
  stat:
    path: /var/lib/vz/template/cache/debian-12-standard_12.0-1_amd64.tar.zst
  register: debian_template_file

- name: Download debian template if not present
  shell: pveam download local debian-12-standard_12.0-1_amd64.tar.zst
  when: not debian_template_file.stat.exists

- name: Create Titanic LXC container
  community.general.proxmox:
    vmid: 100
    node: hp
    api_user: root@pam
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    ostemplate: "local:vztmpl/debian-12-standard_12.0-1_amd64.tar.zst"  # Template name or path
    hostname: titanic
    password: "{{ titanic_password }}"
    storage: "local-lvm"
    cpus: 2
    disk: 100
    memory: 3000
    swap: 0
    tags: "docker"
    pubkey: "{{ ssh_public_key }}"
    netif: '{"net0":"name=eth0,gw=192.168.80.1,ip=192.168.80.21/24,bridge=vmbr0"}'
    unprivileged: true
    onboot: true
    state: "present"
    features:
    - nesting=1
    - fuse=1 
    - keyctl=1

- name: Start titanic LXC container
  community.general.proxmox:
    vmid: 100
    node: hp
    api_user: root@pam
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    state: "started"

- name: Check if ubuntu iso file exists
  stat:
    path: /var/lib/vz/template/iso/ubuntu-20.04.6-desktop-amd64.iso
  register: ubuntu_iso

- name: Download ubuntu iso
  shell: wget https://www.releases.ubuntu.com/focal/ubuntu-20.04.6-desktop-amd64.iso -O /var/lib/vz/template/iso/ubuntu-20.04.6-desktop-amd64.iso
  when: not ubuntu_iso.stat.exists

- name: Check if manjaro iso file exists
  stat:
    path: /var/lib/vz/template/iso/manjaro-sway-22.1.2-230910-linux61.iso
  register: manjaro_iso

- name: Download manjaro sway iso
  shell: wget https://manjaro-sway.download/download?file=manjaro-sway-22.1.2-230910-linux61.iso -O /var/lib/vz/template/iso/manjaro-sway-22.1.2-230910-linux61.iso
  when: not manjaro_iso.stat.exists

- name: Create virgo VM
  community.general.proxmox_kvm:
    vmid: 102
    node: hp
    api_user: root@pam
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    name: virgo
    cpulimit: 0
    cores: 2
    memory: 4000
    sata:
      sata0: 'local-lvm:100,format=raw'
    ide:
      ide0: local:iso/manjaro-sway-22.1.2-230910-linux61.iso,media=cdrom,size=6734336
    bios: ovmf
    efidisk0:
      storage: local-lvm
      format: raw
      efitype: 4m
      pre_enrolled_keys: false
    sshkeys: "{{ ssh_public_key }}"
    nameservers:
      - '1.1.1.1'
    net:
      net0: 'virtio,bridge=vmbr0,tag=77'
    ipconfig:
      ipconfig0: 'ip=192.168.80.22/24'
    onboot: true
    agent: true
  register: virgo

- name: Waiting to start virtual server machine completely
  wait_for:
    timeout: 45
  when: virgo.changed == true

- name: Start VM
  community.general.proxmox_kvm:
    api_user: root@pam
    api_password: "{{ proxmox_api_password }}"
    api_host: "{{ proxmox_api_host }}"
    name: virgo
    node: hp
    state: started
