- name: Copy tailscale install script
  copy:
    dest: /usr/local/bin/tailscale-install.sh
    group: root
    mode: 0744
    owner: root
    src: files/tailscale-install.sh

# Set ip forwarding on in /proc and in the sysctl file and reload if necessary
- name: enable ipv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: enable ipv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Check if tailscale already installed
  stat:
    path: /usr/bin/tailscale
  register: tailscale_bin

- name: Install tailscale
  command: /usr/local/bin/tailscale-install.sh
  when: not tailscale_bin.stat.exists

- name: Start tailscale
  command: tailscale up --accept-dns=false --authkey="{{ tailscale_key }}"
  # when: not tailscale_bin.stat.exists
