---

- name: Download k3s binary x64
  get_url:
    url: https://get.k3s.io
    checksum: sha256:1fa0365382d25b67b67c4891af418ad4dfa8bfc27a817d188054c88f8d910e9d
    dest: /tmp/k3s_install.sh
    owner: root
    group: root
    mode: 0755
