- hosts: prox
  roles:
  - role: roles/proxmox

- hosts: k3s
  roles:
  - role: roles/tailscale
  become: true

- hosts: nfs
  roles:
  - role: roles/nfs

- hosts: k3s
  roles:
  - role: roles/k3s-worker
  become: true
