- hosts: prox
  roles:
  - role: roles/proxmox
  - role: roles/tailscale

- hosts: cosmos
  roles:
  - role: roles/tailscale
  - role: roles/k3s-master
  - role: roles/k8s-init
  - role: roles/cilium
  become: true
