- hosts: prox
  roles:
  - role: roles/proxmox

## TODO:
## Configure cloudflare tunnel

- hosts: cosmos
  roles:
  - role: roles/k3s-master
  - role: roles/k8s-setup
  - role: roles/cilium
  become: true
