- name: Check if k3s already installed
  stat:
    path: /etc/systemd/system/k3s.service
  register: k3s_service_file

- name: Download k3s binary x64
  get_url:
    url: https://get.k3s.io
    checksum: sha256:ff8b7b4028299c878180c1288efa73205c54c7c3fbc2d313fcc666374526d221
    dest: /tmp/k3s_install.sh
    owner: root
    group: root
    mode: 0755
  when: not k3s_service_file.stat.exists

- name: Install k3s
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    INSTALL_K3S_EXEC: 'server --disable traefik --disable servicelb --disable metrics-server --disable-cloud-controller
       --kube-controller-manager-arg=--node-cidr-mask-size-ipv6={{ node_cidr_mask_size_ipv6 }}
       --kube-proxy-arg proxy-mode=ipvs
       --cluster-cidr={{ cluster_cidr }} --service-cidr={{ service_cidr}} --snapshotter native
       --disable-network-policy --flannel-backend=none --node-ip={{ node_ip}} --disable local-storage'
  command: /tmp/k3s_install.sh
  when: not k3s_service_file.stat.exists

- name: Replace kubeconfig vars
  replace:
    path: /etc/rancher/k3s/k3s.yaml
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
  - regexp: 'https://127.0.0.1:6443'
    replace: 'https://{{ master_ip }}:6443'
  - regexp: "default"
    replace: "{{ cluster_name }}"
