- name: install pip3
  apt: name=python3-pip state=present

- name: install pre-requisites
  pip:
    name:
      - openshift
      - pyyaml
      - kubernetes 

- name: Create Flux namespace
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: flux-system
    api_version: v1
    kind: Namespace
    state: present

- name: Create age secret
  kubernetes.core.k8s:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    state: present
    definition:
      apiVersion: v1
      data:
        age.agekey: "{{ age_private_key | b64encode }}"
      kind: Secret
      metadata:
        name: sops-age
        namespace: flux-system
