- name: Create pihole config dir
  file:
    path: /etc/pihole
    state: directory

- name: Copy pihole config
  copy:
    dest: /etc/pihole/setupVars.conf
    group: root
    mode: 0644
    owner: root
    src: files/setupVars.conf

- name: Download pihole installer
  get_url:
    url: https://install.pi-hole.net
    checksum: sha256:60a89cc1c901ef6d591061c0410ccd952bfaba48b62e829be0f88d55cfc48b25
    dest: /tmp/install.sh
    owner: root
    group: root
    mode: 0755

- name: Install pihole
  command: /tmp/install.sh --unattended

- name: Set web password
  shell: pihole -a -p "{{ pihole_web_password }}"
