- name: Install packages
  community.general.pacman:
    name:
    - open-iscsi
    - nfs-utils
    state: present

- name: Enable iscsi service for longhorn
  ansible.builtin.systemd:
    name: iscsi
    enabled: true
  become: true

- name: Start iscsi
  ansible.builtin.systemd:
    state: started
    name: iscsi
  become: true

- name: Check if k3s already installed
  stat:
    path: /etc/systemd/system/k3s.service
  register: k3s_service_file

- name: Download k3s binary x64
  get_url:
    url: https://get.k3s.io
    checksum: sha256:ff8b7b4028299c878180c1288efa73205c54c7c3fbc2d313fcc666374526d221
    dest: /tmp/k3s_install.sh
    owner: root
    group: root
    mode: 0755
  when: not k3s_service_file.stat.exists

- name: Install k3s
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
    K3S_URL: "https://{{ master_ip }}:{{ master_port }}"
    K3S_TOKEN: "{{ k3s_token }}"
  command: /tmp/k3s_install.sh
  when: not k3s_service_file.stat.exists
